### PR TITLE
replace `ghc` dependency with `ghc-lib`

### PR DESCRIPTION
**Pull request by peterbecich**
I think this may solve an issue: https://github.com/input-output-hk/haskell.nix/issues/1829#issue-1534542637
```
DocTests: <command line>: cannot satisfy -package ghc
```

https://hackage.haskell.org/package/ghc-lib

I will confirm shortly if it actually solves the issue. Thanks

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
Thanks for the PR, I'll have CI run _but_ I'll be upfront and say that I don't expect to merge this. `ghc-lib` is a very heavy dependency, and it seems to me that `ghc` not being accessible as a library is a Nix issue.

Could you run with `--debug` and post the logs here? I'm interested to see where `doctest-parallel` fails. Also, if you start a nix shell and do `ghci -package ghc` and try to import something from that package, does it work?

I'm eager to get Nix support; I've already [invested some time](https://github.com/martijnbastiaan/doctest-parallel/blob/cfadbd95748ee00bab15b7ab00ccae3d86b7add9/src/Test/DocTest/Internal/Nix.hs) in getting Nix to work, but it all seems kinda flaky (pun intended :-)).

**Comment by martijnbastiaan** [comment]
If this happened after upgrading to the latest `doctest-parallel` it might be worth trying to disable Nix support with `--no-nix`.

**Comment by martijnbastiaan** [comment]
I'm assuming this PR is obsolete given https://github.com/haskell/hackage-server/pull/1154#issuecomment-1426929515. Feel free to re-open.

**Comment by peterbecich** [comment]
Yes, thanks, sorry I didn't follow up on this

**Pull request closed without merging**
